language: c

env:
  - APP=apache2
  - APP=arduino
  - APP=basics
  - APP=chrome
  - APP=deluge
  - APP=docker.io docker-compose
  - APP=eagle
  - APP=hamachi
  - APP=java
  - APP=mate
  - APP=mysql-workbench
  - APP=nodejs
  - APP=openssh-server
  - APP=php7
  - APP=phpstorm
  - APP=quassel
  - APP=secondlife
  - APP=skype
  - APP=slack
  - APP=spotify
  - APP=steam
  - APP=telegram
  - APP=whatpulse
  - APP=zsh
  - APP=update-and-upgrade

matrix:
  allow_failures:

script:
  - ./installifier $APP

notifications:
  email:
    - matthew@baggett.me
  slack: thruio:m7cGYXmdz261AkGDfiRVBHmY

sudo: required
